rm -rf bld
mkdir -p bld && cd bld
cmake -G "Ninja" -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Debug -DCOIN_BUILD_SHARED_LIBS=0 -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCOIN_BUILD_EXAMPLES=1 -DHAVE_VRML97=1 -DCOIN_BUILD_EGL=1 -DCOIN_USE_BGFX_RENDERER=0 ..
